#!/usr/bin/env python

import logging
import signal
# import socket
import sys
import tornado

from argparse import (ArgumentParser,
                      ArgumentDefaultsHelpFormatter)
from src.katcp_server import BLBackendInterface
# from src.effelsberg.config import get_nodes


def cli(prog):
    usage = "{} [options]".format(prog)
    description = 'start BLUSE KATCP server'

    parser = ArgumentParser(usage=usage,
                            description=description,
                            formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument(
        '--ip',
        type=str,
        default="localhost",
        help='fixed IP of localhost system')
    parser.add_argument(
        '-p', '--port',
        type=int,
        default=5000,
        help='port number to bind to')
    parser.add_argument(
        '--nodeset',
        dest='nodeset',
        type=str,
        default="effelsberg",
        help='name of the nodeset to use')

    # Options for development and testing
    title = "development and testing"
    description = "additional convenience settings"
    group = parser.add_argument_group(title=title,
                                      description=description)
    group.add_argument(
        '--debug',
        action='store_true',
        help='verbose logger output for debugging')

    return parser.parse_args()


# Set up logging to console and file.
def set_logger(log_level=logging.DEBUG):
    FORMAT = "[ %(levelname)s - %(asctime)s - %(filename)s:%(lineno)s] %(message)s"
    logging.basicConfig(format=FORMAT)
    log = logging.getLogger("BLUSE.interface")
    log.setLevel(log_level)

    return log


@tornado.gen.coroutine
def on_shutdown(ioloop, server):
    log.info("Shutting down server")
    yield server.stop()
    ioloop.stop()


if __name__ == "__main__":
    args = cli(sys.argv[0])
    if args.debug:
        # note: debug logging will only go to logfile
        log_level = logging.DEBUG
    else:
        log_level = logging.INFO

    log = set_logger(log_level=log_level)
    log.info("Starting BLBackendInterface instance")

    ioloop = tornado.ioloop.IOLoop.current()
    server = BLBackendInterface(args.ip, args.port)
    signal.signal(signal.SIGINT,
                  lambda sig, frame: ioloop.add_callback_from_signal(
                      on_shutdown, ioloop, server))

    def start():
        server.start()
        log.info("Listening at {0}, Ctrl-C to terminate server".format(server.bind_address))
        # nodes = get_nodes(opts.nodeset)
        # for node in nodes:
        #     ip = socket.gethostbyname(node["host"])
        #     print node["host"],ip,node["port"]
        #     server._add_node(node["host"],ip,node["port"])
    ioloop.add_callback(start)
    ioloop.start()
