#!/usr/bin/env python

import logging
import signal
import sys

from src.katportal_server import BLKATPortalClient

log = logging.getLogger("BLUSE.interface")


def on_shutdown():
    # TODO: uncomment when you deploy
    # notify_slack("KATPortal module at MeerKAT has halted. Might want to check that!")
    log.info("Shutting Down Katportal Clients")
    sys.exit()


def main():
    FORMAT = "[ %(levelname)s - %(asctime)s - %(filename)s:%(lineno)s] %(message)s"
    # logger = logging.getLogger('reynard')
    logging.basicConfig(format=FORMAT)
    log.setLevel(logging.DEBUG)
    log.info("Starting Katportal Client")

    client = BLKATPortalClient()
    signal.signal(signal.SIGINT, lambda sig, frame: on_shutdown())
    client.start()


if __name__ == '__main__':
    main()
